In [12]:
import pandas as pd
import numpy as np

In [13]:
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [14]:
df = pd.read_csv('train.csv', usecols=['Age', 'Fare', 'Survived'])
df.sample(5)

     Survived   Age     Fare
447         1  34.0  26.5500
164         0   1.0  39.6875
248         1  37.0  52.5542
707         1  42.0  26.2875
22          1  15.0   8.0292

In [15]:
df.dropna(inplace=True)

In [16]:
df.shape

(714, 3)

In [17]:
df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500